name       : umockdev
version    : 0.16.3
release    : 7
source     :
    - https://github.com/martinpitt/umockdev/releases/download/0.16.3/umockdev-0.16.3.tar.xz : 4e31f1aadcfc98f873a6c31be655d6763f21c7fc21b1a7537e8af84b6c785363
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Mock hardware devices for unit tests and bug reports
description: |
    umockdev mocks Linux devices for creating integration tests for hardware related libraries and programs. It also provides tools to record the properties and behaviour of particular devices, and to run a program or test suite under a test bed with the previously recorded devices loaded. This allows developers of software like gphoto or libmtp to receive these records in bug reports and recreate the problem on their system without having access to the affected hardware.
optimize   :
    - no-symbolic
patterns   :
    - docs : /usr/share/doc
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpcap)
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %meson_build
install    : |
    %meson_install
check      : |
    %meson_check
