name       : umockdev
version    : 0.9.4
release    : 1
source     :
    - https://github.com/martinpitt/umockdev/archive/0.9.4.tar.gz : 9f13e8a836ef36158e2cc2b679cb99639e1f68a430b04fbe4dd07d3cb2b32a75
license    : LGPL-2.1
component  : programming.library
summary    : Mock hardware devices for unit tests and bug reports
description: |
    umockdev mocks Linux devices for creating integration tests for hardware
    related libraries and programs. It also provides tools to record the
    properties and behaviour of particular devices, and to run a program or
    test suite under a test bed with the previously recorded devices loaded.
    This allows developers of software like gphoto or libmtp to receive these
    records in bug reports and recreate the problem on their system without
    having access to the affected hardware.
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk-doc)
    - vala
optimize   :
    - no-symbolic
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
