name       : umockdev
version    : 0.14.1
release    : 6
source     :
    - https://github.com/martinpitt/umockdev/releases/download/0.14.1/umockdev-0.14.1.tar.xz : ffb6134667f510a146b533076eb1a316392c7902a4ec593080de9fb53393e8bc
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Mock hardware devices for unit tests and bug reports
description: |
    umockdev mocks Linux devices for creating integration tests for hardware
    related libraries and programs. It also provides tools to record the
    properties and behaviour of particular devices, and to run a program or
    test suite under a test bed with the previously recorded devices loaded.
    This allows developers of software like gphoto or libmtp to receive these
    records in bug reports and recreate the problem on their system without
    having access to the affected hardware.
optimize   :
    - no-symbolic
patterns   :
    - docs : /usr/share/doc
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install
