name       : umockdev
version    : 0.12.1
release    : 4
source     :
    - https://github.com/martinpitt/umockdev/releases/download/0.12.1/umockdev-0.12.1.tar.xz : a2ed2e77cdefe20798e040b13b0ae0e6366ed127a25ccf1387e659a75295a5c3
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Mock hardware devices for unit tests and bug reports
description: |
    umockdev mocks Linux devices for creating integration tests for hardware
    related libraries and programs. It also provides tools to record the
    properties and behaviour of particular devices, and to run a program or
    test suite under a test bed with the previously recorded devices loaded.
    This allows developers of software like gphoto or libmtp to receive these
    records in bug reports and recreate the problem on their system without
    having access to the affected hardware.
optimize   :
    - no-symbolic
patterns   :
    - docs : /usr/share/doc
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install
